name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install Poetry
        run: pip install poetry
      - name: Install dependencies
        run: poetry install
      - name: Run linters
        run: poetry run ruff check .
      - name: Run format check
        run: poetry run black --check .
      - name: Run type checks
        run: poetry run mypy .
      - name: Run tests
        run: poetry run pytest
